changed indent

diff --git a/tmNIDS b/tmNIDS
--- a/tmNIDS
+++ b/tmNIDS
@@ -3,104 +3,104 @@
 # Define all the tests
 
 test_uid () {
-    curl -s http://testmynids.org/uid/index.html > /dev/null
+  curl -s http://testmynids.org/uid/index.html > /dev/null
 }
 
 test_basicauth () {
-    curl -s -H "Authorization: Basic cm9vdDpyb290" testmynids.org > /dev/null
+  curl -s -H "Authorization: Basic cm9vdDpyb290" testmynids.org > /dev/null
 }
 
 test_useragent () {
-    curl -s -A "BlackSun" testmynids.org > /dev/null
-    curl -s -A "HttpDownload" testmynids.org > /dev/null
-    curl -s -A "agent" testmynids.org > /dev/null
-    curl -s -A "MSIE" testmynids.org > /dev/null
-    curl -s -A "JEDI-VCL" testmynids.org > /dev/null
+  curl -s -A "BlackSun" testmynids.org > /dev/null
+  curl -s -A "HttpDownload" testmynids.org > /dev/null
+  curl -s -A "agent" testmynids.org > /dev/null
+  curl -s -A "MSIE" testmynids.org > /dev/null
+  curl -s -A "JEDI-VCL" testmynids.org > /dev/null
 }
 
 test_badcas () {
-    curl -s https://edellroot.badssl.com/ > /dev/null
-    curl -s https://superfish.badssl.com/ > /dev/null
+  curl -s https://edellroot.badssl.com/ > /dev/null
+  curl -s https://superfish.badssl.com/ > /dev/null
 }
 
 test_tor () {
-    # Sample response with .onion
-    dig a 3wzn5p2yiumh7akj.onion @8.8.8.8 > /dev/null
+  # Sample response with .onion
+  dig a 3wzn5p2yiumh7akj.onion @8.8.8.8 > /dev/null
 
-    # Retrieve Tor IP list and connect to 10
-    curl -s https://raw.githubusercontent.com/SecOps-Institute/Tor-IP-Addresses/master/tor-nodes.lst -o /tmp/tor.list >/dev/null 2>&1
-    # Randomize it
-    sort --random-sort /tmp/tor.list > /tmp/randomtor.list
-    # Connect to them
-    head -n10 /tmp/randomtor.list | while read line; do nc -z -w 4 $line 443 2>&1; done
-    # Clean temporary files
-    rm /tmp/tor.list
-    rm /tmp/randomtor.list
+  # Retrieve Tor IP list and connect to 10
+  curl -s https://raw.githubusercontent.com/SecOps-Institute/Tor-IP-Addresses/master/tor-nodes.lst -o /tmp/tor.list >/dev/null 2>&1
+  # Randomize it
+  sort --random-sort /tmp/tor.list > /tmp/randomtor.list
+  # Connect to them
+  head -n10 /tmp/randomtor.list | while read line; do nc -z -w 4 $line 443 2>&1; done
+  # Clean temporary files
+  rm /tmp/tor.list
+  rm /tmp/randomtor.list
 }
 
 test_exe () {
-    curl -s http://testmynids.org/exe/calc.exe -o /tmp/calc.exe
+  curl -s http://testmynids.org/exe/calc.exe -o /tmp/calc.exe
 }
 
 test_pdf () {
-    curl -s testmynids.org/pdf/pdf.pdf -o /tmp/pdf.pdf 
+  curl -s testmynids.org/pdf/pdf.pdf -o /tmp/pdf.pdf 
 }
 
 test_22scan () {
-    nc testmynids.org 22 -w3 > /dev/null
+  nc testmynids.org 22 -w3 > /dev/null
 }
 
 test_miscdns () {
-    dig sinkhole.cert.pl @8.8.8.8 > /dev/null
-    dig nic.su @8.8.8.8 > /dev/null
-    dig invalid.no-ip.com @8.8.8.8 > /dev/null
+  dig sinkhole.cert.pl @8.8.8.8 > /dev/null
+  dig nic.su @8.8.8.8 > /dev/null
+  dig invalid.no-ip.com @8.8.8.8 > /dev/null
 }
 
 test_md5rsa () {
-    # This test is made possible by Barracuda, as they still believe MD5 in certificates is OK
-    for ip in 64.235.158.{25..30}
-        do
-            echo Q | openssl s_client -connect ${ip}:443 -tls1 > /dev/null 2>&1
-        done
+  # This test is made possible by Barracuda, as they still believe MD5 in certificates is OK
+  for ip in 64.235.158.{25..30}
+    do
+      echo Q | openssl s_client -connect ${ip}:443 -tls1 > /dev/null 2>&1
+    done
 }
 
-# Presentation and menu
+# Interactive mode - Presentation and menu
 
 while true; do
-    options=("Linux UID" "HTTP Basic Authentication" "HTTP Malware User-Agent" "Bad Certificate Authorities" "Tor .onion DNS response and known IPs connection" "EXE or DLL download over HTTP" "PDF download with Embedded File" "Simulate SSH Outbound Scan" "Miscellaneous domains (TLD's, Sinkhole, DDNS, etc)" "MD5 in TLS Certificate Signature" "CHAOS! RUN ALL!" "Quit!")
+  options=("Linux UID" "HTTP Basic Authentication" "HTTP Malware User-Agent" "Bad Certificate Authorities" "Tor .onion DNS response and known IPs connection" "EXE or DLL download over HTTP" "PDF download with Embedded File" "Simulate SSH Outbound Scan" "Miscellaneous domains (TLD's, Sinkhole, DDNS, etc)" "MD5 in TLS Certificate Signature" "CHAOS! RUN ALL!" "Quit!")
 
-    clear
+  clear
 
-    echo " _             _   _ _____ _____   _____ "
-    echo "| |           | \ | |_   _|  __ \ / ____|"
-    echo "| |_ _ __ ___ |  \| | | | | |  | | (___  "
-    echo "| __|  _   _ \| .   | | | | |  | |\___ \ "
-    echo "| |_| | | | | | |\  |_| |_| |__| |____) |"
-    echo " \__|_| |_| |_|_| \_|_____|_____/|_____/ "
+  echo " _             _   _ _____ _____   _____ "
+  echo "| |           | \ | |_   _|  __ \ / ____|"
+  echo "| |_ _ __ ___ |  \| | | | | |  | | (___  "
+  echo "| __|  _   _ \| .   | | | | |  | |\___ \ "
+  echo "| |_| | | | | | |\  |_| |_| |__| |____) |"
+  echo " \__|_| |_| |_|_| \_|_____|_____/|_____/ "
 
-    echo ""
-    echo "tmNIDS - NIDS detection tester - @0xtf"
-    echo "Project: https://github.com/0xtf/testmynids.org"
-    echo ""
-    echo "Choose which test you'd like to run: "
-    echo ""
-    select opt in "${options[@]}"; do
-        case $REPLY in
-            1) test_uid; break ;;
-            2) test_basicauth; break ;;
-            3) test_useragent; break ;;
-            4) test_badcas; break ;;
-            5) test_tor; break ;;
-            6) test_exe; break ;;
-            7) test_pdf; break ;;
-            8) test_22scan; break ;;
-            9) test_miscdns; break ;;
-            10) test_md5rsa; break ;;
-            11) test_uid; test_basicauth; test_useragent; test_badcas; test_tor; test_exe; test_pdf; test_22scan; test_miscdns; test_md5rsa; break ;;
-            12) break 12 ;;
-            *) echo "Invalid option!" >&2
-        esac
-    done
+  echo ""
+  echo "tmNIDS - NIDS detection tester - @0xtf"
+  echo "Project: https://github.com/0xtf/testmynids.org"
+  echo ""
+  echo "Choose which test you'd like to run: "
+  echo ""
+  select opt in "${options[@]}"; do
+    case $REPLY in
+      1) test_uid; break ;;
+      2) test_basicauth; break ;;
+      3) test_useragent; break ;;
+      4) test_badcas; break ;;
+      5) test_tor; break ;;
+      6) test_exe; break ;;
+      7) test_pdf; break ;;
+      8) test_22scan; break ;;
+      9) test_miscdns; break ;;
+      10) test_md5rsa; break ;;
+      11) test_uid; test_basicauth; test_useragent; test_badcas; test_tor; test_exe; test_pdf; test_22scan; test_miscdns; test_md5rsa; break ;;
+      12) break 12 ;;
+    *) echo "Invalid option!" >&2
+  esac
+  done
 done
 
 echo ""
